name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: make
      working-directory: ./Roldan_Andrade_Antonio/P4/
      run: make 
    - name: checksauto
      working-directory: ./Roldan_Andrade_Antonio/P4/
      run: ./test-P4-auto 
